name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: gradle/wrapper-validation-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew --build-cache test build
